apiVersion: v1
kind: Service
metadata:
  name: space-service
spec:
  type: LoadBalancer  # Use NodePort or ClusterIP for internal services
  selector:
    app: space
  ports:
    - protocol: TCP
      port: 8000       # Port exposed by the service
      targetPort: 8000 # Container port to route traffic to

